### ISSUE TITLE
The output of the code

### ISSUE THREAD

**Issue by BingHan0458** [GPrathap/forest_gen#1]
Dear Prof. GPrathap,
Thank you so much for this lightweight open source code of forest_gen, I run it using `./genForests.sh 1 10 0.2 0.2` but there are no output after:
```
generating worlds
Generating octomap of forest0

```
I don't know whether it runs for long or not? I don't know if it's because this program takes a long time to run or something else?
Look forward to your reply， thank you very much!
Bing Han

**Comment by GPrathap** [comment]
Have you installed this ROS pakage https://github.com/GPrathap/sim_gazebo_plugins.git ? you probably missed it (it is mentioned in the README)

Once you install  this package, after running `genForests.sh`  , check `rosservice list` there should be `/world/build_octomap` 

Let me know once you tried this

**Comment by BingHan0458** [comment]
Sure, I download it and put it in the same dir, but it doesn't work.
So how to install this package?
Thank you very much!

**Comment by GPrathap** [comment]
Place it inside your ros workspace, i.e.,  `ros_workspace/src` and build either using `catkin_make` or `catkin build` and get a new  terminal and try again

**Comment by BingHan0458** [comment]
Thank you very much! It works.
But I also have some questions as follows:
Is it just a dataset about forest? How to get the output of point cloud format?
And if I want to add some multi-agent collision avoidance algorithms, such as  Reinforcement lLarning ,what should I do?
Could you give me some advance?
Thank you very much!

**Comment by GPrathap** [comment]
Yeap, this repo can be used to generate a set of random worlds where you can be used for validation purpose, write to me on Gmail: ggeesara@gmail.com, I may try to hep you
